### ISSUE TITLE
NGE Housing Lot Size/Correlation to Actual Size of House

### ISSUE THREAD

**Issue by Bommbur** [Thrax989/SWGFlurry#10]
atat_house.lua		              5 Lots Good
bespin_house.lua	              5 Lots Good
commando_house.lua	      5 Lots Not Good Should be 2
emperors_house.lua	      5 Lots Not Good Should be 2
gen_large_win_01.lua	      5 Lots Good
gen_large_win_02.lua	      5 Lots Good
gen_medium_win_01.lua	      5 Lots Not Good Should be 3
gen_medium_win_02.lua       5 Lots Not Good Should be 3
gen_small_win_01.lua	      5 Lots Not Good Should be 2
gen_small_win_02.lua	      5 Lots Not Good Should be 2
hangar_house.lua	              5 Lots Good
jabbas_house.lua  	              5 Lots Good
jedi_house.lua	                      5 Lots Not Good Should be 2
musty_house.lua	              5 Lots Good
nab_small_win_01.lua	      2 Lots Good
ns_hut_house.lua	              2 Lots Good
rebel_house.lua	              5 Lots Not Good Should be 2
relaxation_house.lua	      5 Lots Not Good Should be 2
sandcrawler_house.lua	      5 Lots Good
sith_house.lua	                      5 Lots Not Good Should be 2
sm_hut_house.lua	              2 Lots Good
tat_small_win_01.lua	      2 Lots Good
tree_house.lua	                      5 Lots Good
vehicle_house.lua	              5 Lots Good
vipbunker_house.lua	      5 Lots Good
yoda_house.lua	              2 Lots Good
yt1300_house.lua	              5 Lots Good

**Comment by mhutcherson** [comment]
I updated all the proposed houses. Issue can be closed.
