### ISSUE TITLE
Barrel For Chefs

### ISSUE THREAD

**Issue by Bommbur** [Thrax989/SWGFlurry#13]
Values on Min/Max should be adjusted to 0, 0, 6 to effect the change thats necesary to make these double the value of casks that the material requirement calls out for.

https://github.com/Thrax989/SWGFlurry/blob/master/MMOCoreORB/bin/scripts/object/tangible/component/food/container_barrel.lua

object_tangible_component_food_container_barrel = object_tangible_component_food_shared_container_barrel:new {

	numberExperimentalProperties = {1, 1, 1},
	experimentalProperties = {"XX", "XX", "XX"},
	experimentalWeights = {1, 1, 1},
	experimentalGroupTitles = {"null", "null", "null"},
	experimentalSubGroupTitles = {"null", "null", "quantity_bonus"},
	experimentalMin = {0, 0, 1},
	experimentalMax = {0, 0, 1},
	experimentalPrecision = {0, 0, 0},
	experimentalCombineType = {0, 0, 1},
}

**Comment by mhutcherson** [comment]
Issue fixed. Can be closed.

**Comment by Thrax989** [comment]
This has been patch thank you . https://github.com/Thrax989/SWGFlurry/commit/6a7b90c9fc7bb24b55c4991786964e45588e99e2
