### ISSUE TITLE
Re Adjust New Pet Calculations

### ISSUE THREAD

**Issue by Thrax989** [Thrax989/SWGFlurry#15]
Here are the commits for the code reset for the Creature handler and Bio engineer code.

https://github.com/Thrax989/SWGFlurry/commit/c85b6b253fb347affb30e15a83eb57c33732aad4

https://github.com/Thrax989/SWGFlurry/commit/0af1cc18ccac9df0f31568f9a1f570e8efbc59ca

These systems will need to be re added in with more balanced approach . you can compare the old changes from PP to the default code that is currently in place.

**Comment by bobvious** [comment]
Working on them.   I got pets scaled up to 85, but that broke the CL10's.   I'm working on the math for an updated formula.

**Comment by sygnum** [comment]
Any eta on this, eager to do some testing myself :)

**Comment by Thrax989** [comment]
once someone submits the changes ill apply them they are back to default at the moment

**Comment by sygnum** [comment]
If CH tamed pets are to be on par with BE created pets or atleast viable in a lesser capacity they need to seriously be tweak.  They also are not all on part.  Pretty decent different from a regular rancor (50) and a mutated rancor (75),

**Comment by sygnum** [comment]
Can only Sample BioEngineered pets 3 times before pets disappear.  Also has a chance to fail for some reason.

**Comment by sygnum** [comment]
The HAM of the tamed creatures is still really low.. 11000 on the blurrg that I tamed, capped at 50.. 2706 damage. Random resist, nothing great.

**Comment by bobvious** [comment]
Added some more tamable creatures at level 85,   Closing this issue for now.   We will revisit balance as needed going forward.
