### ISSUE TITLE
Revisit Bonuses to Player City Structures and NGE Houses

### ISSUE THREAD

**Issue by bobvious** [Thrax989/SWGFlurry#19]
I'd like to propose the following bonuses, because I believe what was committed did not make sense across the board.  (UPDATED)

**Houses**

Non-NGE Houses - Normal bonuses to medical and entertainer (100)

NGE Houses - 110 to Medical, 125 to Ent Buffs (Duration) - This will allow variety for people who want to use NGE houses as cantinas.    Doctors will be able to buff with droids in the field for the same amount.   Experimentation bonus at 5 (as it is currently), assembly and repair at 20 (down from 50).   This gives a reason to gain additional assembly and repair bonuses from FS crafting (additional +20 available).

**Cantina's and Medical Centers**

NPC City Medical Center and Cantina's - 110 Medical on med centers, 125 on entertainer buffs.

Player City Cantina's - 110 medical, 125 entertainer

Player City Medical Centers - 110 medical

**Comment by qrave** [comment]
I feel NPC buildings should offer higher bonuses than player buildings to drive buffers and players into the open world more. Only coroner and theed or something.

By doing this; it would force more inter-guild, inter-faction social interaction

**Comment by Bommbur** [comment]
The decision to remove the bonuses for ent/doc from those buildings was to get folks back in the buildings they were supposed to be in, cantina's/med centers, as far as lowering assembly/repair to make room for FS I personally hate the idea of forcing people to do anything Jedi related for crafting, if you want 2 extra experimentation points go for it, other than that they shouldnt HAVE to get jedi to make decent stuff.

**Comment by bobvious** [comment]
We had a whole group on last night who feel like we were removing too many things that people liked on PP that were not creating an imbalance.   My thought is to bump NPC city cantinas and medcenters equal to player city structures and NGE houses to make them viable alternatives, but not force a chance in playstyle.  People like using the NGE houses so why make them stop?   The amazing and repair chances are just chances for success and not a major issue like the experimentation.

**Comment by bobvious** [comment]
I'm going to close this for now and push the changes to test.   This is something we can always tweak in the future if our population exceeds our wildest expectations.
