### ISSUE TITLE
Commando special attack range back to 64m.

### ISSUE THREAD

**Issue by ElectroPulsed** [Thrax989/SWGFlurry#26]
The special attacks from commando used to have a range of 64m on PP. Now they have a range of 16m.

**Comment by Maanten** [comment]
Not sure what specials you are referring to but flamethrower single was 16m on pp.

**Comment by ElectroPulsed** [comment]
FlameSingle1/FlameSingle2, FlameCone1/FlameCone2. Havent tested Acid specials yet. In Nov. 2016 it was 64m range. If it is intended to be now on 16m this issue can be closed.
