### ISSUE TITLE
Lair Searches

### ISSUE THREAD

**Issue by Bommbur** [Thrax989/SWGFlurry#34]
Not sure if this is just throwing a bad command or what, I receive eggs and live samples like I should but it also throws out occasionally 'Unable to create loot for lootgroup' I cant find the lootgroup for lairs so not sure what is missing, only received live sample jars and eggs so far.

**Comment by Thrax989** [comment]
are you missing anything from looting lairs? or this is just a error message poping up?

**Comment by bobvious** [comment]
If have seen this which searing lairs also.  I'll see if I can replicate.

**Comment by bobvious** [comment]
Here's the relevant code, I'll see if I can figure it out.  
	} else if (forageType == ForageManager::LAIR) { //Lair Search
		dice = System::random(109);
		level = 1;
		float creatureHarvestingSkill = player->getSkillMod("creature_harvesting") + 1; // Makes it 1 even if it's NULL
		
		dice *= creatureHarvestingSkill / 450 + 1;

		if (dice >= 0 && dice < 40) { // Live Creatures
			lootGroup = "forage_live_creatures";
		}
		else if (dice > 39 && dice < 110) { // Eggs
			resName = "meat_egg";
			if(forageGiveResource(player, forageX, forageY, planet, resName)) {
				player->sendSystemMessage("@lair_n:found_eggs");
				return true;
			} else {
				player->sendSystemMessage("@lair_n:found_nothing");
				return false;
			}
		}

		if(!lootManager->createLoot(inventory, lootGroup, level)) {
			player->sendSystemMessage("Unable to create loot for lootgroup " + lootGroup);
			return false;
		}

		player->sendSystemMessage("@lair_n:found_bugs");
		return true;
	}

	player->sendSystemMessage("@skl_use:sys_forage_success");
	return true;
}
