### ISSUE TITLE
Skill Points

### ISSUE THREAD

**Issue by Kyushujack** [Thrax989/SWGFlurry#43]
The game doesn't stop you from from training more after you run out of skill points.  You can continue and it just shows negative skill points.  People are going to abuse this and overpower themselves.

**Comment by Bommbur** [comment]
certain skills? it wouldnt let me receive training when I ran out earlier? I had to drop other boxes to do so

**Comment by Kyushujack** [comment]
My wife has some artisan then mastered all of the entertainer tree.  She pushed into negative territory masterin Musician.

**Comment by terminator2014** [comment]
this will depend on the toon created was it  made before you did the fix ? i ran same problem in my sons server making template with negative skill points then reverted back to 250 sp but new players couldn't go negative but my toon made before change could still train in neg skill points

**Comment by Thrax989** [comment]
this is not how this works. it only goes - when your using FS skills. just a visual bug you cant gain any other skills other then the 0 skill pointed fs skills.
