### ISSUE TITLE
Squad Leader: unable to gain xp on Naboo

### ISSUE THREAD

**Issue by Ayzoz** [Thrax989/SWGFlurry#44]
something to do with - z axis, SL fine any other planet.

**Comment by Thrax989** [comment]
Correct I will get to this soon best approach for now for the player is to Have squad leader on corellia and have the group that is getting xp for the squad leader to do that on lok . Make sure the squad leader is leader as well. This works currently for a few people grinding.

**Comment by bobvious** [comment]
There is Z-axis bug if SL is below 0 on the Z-axis, I couldn't figure out why it happens.
