### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by shoted45** [Thrax989/SWGFlurry#447]
Been trying to build the server for a while now and I keep getting this error. Any help would be greatly appreciated. 

cc1plus: all warnings being treated as errors
Makefile:8196: recipe for target 'server/zone/objects/tangible/component/lightsaber/LightsaberCrystalComponentImplementation.o' failed
make[3]: *** [server/zone/objects/tangible/component/lightsaber/LightsaberCrystalComponentImplementation.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/vagrant/Desktop/swg new/MMOCoreORB/build/unix/src'
Makefile:426: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vagrant/Desktop/swg new/MMOCoreORB/build/unix'
Makefile:367: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vagrant/Desktop/swg new/MMOCoreORB/build/unix'
Makefile:57: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by Thrax989** [comment]
are you using the engine that is in this repo's directory? we are still using publish 9, 

Deleting your MMOCoreORB / MMOEngine folders and replacing it with ours works just fine
would need to do a full build after 
make config 
make clean
make idl
make build

**Comment by shoted45** [comment]
Hey Thrax thanks for the reply, yes I am using the files from your repo. I am deleting everything out of the folders that ZonamaDev creates and then trying to rebuild with the files from here. I am assuming that this can work over the ZonamaDev VM base? I've tried to build through EmuYoda server control, and directly using the terminal commands

**Comment by Gargash** [comment]
Ok, So I am having issues with SWGFlurry as well building after several attempts. I am trying to get a content rich server, I can play with my kids.

My process has been this...... 

pull ZonamaDev VM via GitBash
complete setup except building
powerdown VM change to 8gb ram and 4 cores with bridged adaptor
powered VM back on
deleted Core3 and Engine 
delete /home/vagrant/ZonamaDev/fasttrack/scripts/
Download all required files for SWGFlurry
Move SWGFlurry Core3 and Engine to respective folders
-In Terminal
cd /home/vagrant/workspace/Core3/MMOCoreORB
make config
make clean
make idl
make build

This is the furthest I have made it with the new error being

Makefile:8196: recipe for target 'server/zone/managers/player/PlayerManagerImplementation.o' failed
make[3]: *** [server/zone/managers/player/PlayerManagerImplementation.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/vagrant/workspace/Core3/MMOCoreORB/build/unix/src'
Makefile:426: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vagrant/workspace/Core3/MMOCoreORB/build/unix'
Makefile:367: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/vagrant/workspace/Core3/MMOCoreORB/build/unix'
Makefile:57: recipe for target 'build' failed
make: *** [build] Error 2

All instances are both Master and Publish9. I have referred to several guides from SWGMTG and SWGEMU as well as your Git... unfortunatlly not sure where my hang up is. Any advice is welcome. I hope I included enough detail for anyone to know what is going on.

**Comment by Thrax989** [comment]
Ill see if this weekend I can get a fully compiled Image uploaded so you guys can just download the image and run the server with all the files in order, ill update the guides on here as well, Sorry about that. Ill make a video guide as well just need to put the time together. 


If you have any other questions about the current server build or anything involved in the code you can always ask me here as well.

**Comment by Thrax989** [comment]
<img src="https://i.imgur.com/QeK2teo.png"> I just did a full rebuild with the engine as long as you copy and paste the linux64 Lib Over the Unix Lib then do a complete build it works just fine .

**Comment by Gargash** [comment]
Did as Advised still no dice
also changed permissions to ensure that wasn't an issue

![build fail](https://user-images.githubusercontent.com/1191400/44250650-c40d6000-a1ba-11e8-90ba-27b3b5770a4b.PNG)

**Comment by Thrax989** [comment]
Let me Rebuild my SRC to make sure that its all error free, I may have forgotten to update/push some fix's from my local. I'll reply once I've fully rebuilt.

**Comment by Thrax989** [comment]
Yea my fault, Ill make sure "Master" is stable from now on, been working on a few things last 2 weeks forgot to merge some of the fix's that I left out from my last pull request.

**Comment by Gargash** [comment]
Did a Git Clone, Del, Replaced with new pull.. building report back.

**Comment by Thrax989** [comment]
For some reason editing comments did not inform me that you replied, Ill take a look now one moment I am still actually rebuilding so I should be caught up soon to you, Yea recently I added in a bunch of new jedi stuff I will push the last bit of fix's here in a few once I've caught up with my rebuild.

**Comment by Thrax989** [comment]
that Not check should work just fine I have the same one and just built just fine, if you scroll up are there any other errors? try make build and see if it shows any other errors.

**Comment by Gargash** [comment]
Did a full suite of makes, Terminal output attached. Looking over it myself, as well. Had to edit the terminal preferences for good output.
[New Text Document.txt](https://github.com/Thrax989/SWGFlurry/files/2298066/New.Text.Document.txt)

**Comment by Thrax989** [comment]
Try and manually download the repo, click the green button clone/download Download the files as a zip. On your dev environment open up downloads folder then right click the file and extract to that location. open that folder up and copy the SRC only. go to you main core3 folder then delete your SRC folder and replace it with the manual downloaded one. Then try a full rebuild
make config
make clean
make idl
make build
Trying to see if the git pull messed something up since it works just fine for me and the code error is correct on my side.

**Comment by Gargash** [comment]
still same error after pull

../../../src/server/zone/objects/tangible/component/lightsaber/LightsaberCrystalComponentImplementation.cpp:405:28: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
  if (!jedi->getJediState() >= 1) {
                                        ^~

at a loss cause code looks right

**Comment by Thrax989** [comment]
did you manually do the above or just a git pull?

**Comment by Gargash** [comment]
Manually downloaded this time.... No git pull.

**Comment by Thrax989** [comment]
Codes correct works fine on my end , Try and remove the "Not" function from jedi "!" remove that and build

**Comment by Gargash** [comment]
I removed the "!" from if (!jedi->getJediState() >= 1) on line 405, to  (jedi->getJediState() >= 1).... all calls I see reference object "jedi" without "!". it went past but is now erroring on

/src/server/zone/managers/combat/CombatManager.cpp:1585:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  if (defender->isKnockedDown())

**Comment by Gargash** [comment]
changed 
if (defender->isKnockedDown())
		damage *= 1.5f;
to

	if (defender->isKnockedDown())
		damage *= 1.5;

**Comment by Thrax989** [comment]
I just checked that line of code as well and it's correct, I don't get any of these errors you must have something installed on your dev box that's different than mine . Remove that section of code int he combat manager and keep building. We can resolve the errors later once you're fully built.

**Comment by Thrax989** [comment]
Ah your on debian 9 stretch with the updated dependencies I'm using older Publish 9 Zomna with the older deb 8 I don't have up to date dependencies like you. Ill upgrade to stretch once publish 10 is stable but currently I'm on older files. Hence the older Engine builds as well.

**Comment by Gargash** [comment]
I get it...... I'm looking how to pull ZonamaDev 1.4 for it to work now.

**Comment by Gargash** [comment]
So you know, to get the base environment your using release 1.4, the command in Git Bash is
`vagrant init zonama/zonamadev-deb-jessie   --box-version 1.4.5`
then
`vagrant up`
Took me a while to get working as the ZonamaDev curl command for release 1.4 is for old setup doesn't work with newer version of vagrant. might help for instructions to setup. Will Report back after build on Deb 8.

**Comment by Thrax989** [comment]
im uploading the Dev import of the image with snapshot its pretty huge 36 gigs compressed to 17 need to test it then upload it, has all the tres, and database /sql data-tables ready to go all freshly built ill upload it once i test it and i know it works.

**Comment by Thrax989** [comment]
Works 100% fine, builds, starts up and acts like a fresh new server all you do when its imported is create your new account then log into the server under 127.0.0.1 as your local to play Ill reply by once its uploaded.

**Comment by Gargash** [comment]
Sweet man... So I'll just wait.. I'm patient.

**Comment by Thrax989** [comment]
Wont be to much longer, Just waiting for it to upload now. Its pretty simple you download the Image then import it into Virtual box then start and play. Ill write up a quick guide as well on the read me . Thanks for being patient.

**Comment by Gargash** [comment]
see you revised the info... was looking for a link... awesome work FYI... I` had learned most of them from memory of repetition... on top of making notes in case i have to revisit.... but you have it most of it here. Can't wait for all the custom content, Fiance' is excited as she has seen me spend the last week and a half try and figure this out before actually asking for any assistance. Thanks for all your work too.. as stated previously I understand code, went to school for Game Systems Development though have never gotten to use it in any capacity in Missouri.

**Comment by Thrax989** [comment]
Just got it ll done the image is in the read me now along with a few notes on how to use it all.
https://mega.nz/#!GORAASyZ!Pg0IoC_trmPq39dsY4KIBcjHADC0-Fu-vOFkhYywJqY

**Comment by Thrax989** [comment]
When you start the image you can add your new account and password using the yoda GUI. after that its best to do everything manually I don't really like the GUI its pretty slow. Server is pretty straight forward to start up and run from that point on using terminal. If you run into any problems let me know I can assist. Some system on the server may need to be disabled or enabled if you need help with that as well i can help.

**Comment by Thrax989** [comment]
With the Clone image its a brand new server so give it time to load up it loads up all 35 new planets, It has to write the Navi mesh for each one so takes a tiny bit of time the first time booting up , it also writes the new databases for your server as well, I already tested and everything works just fine. Few updates will need to be rolled out later to make it perfect since I've been testing a few things over the month but once i finish that server will be error few nothing major just a few unit test for string names need to be updated. 

I added more stuff to the notes admin commands and commands to start server ect ect.

Server is set up to run on local 127.0.0.1 you can upgrade it to be public if you wanted as well.

Should be good to go if you run into anything reply here so i can fix it or address it.

**Comment by Thrax989** [comment]
One thing I noticed you will need to increase the 2 gigs of ram to a bit more if you want to run all 35 planets, i bumped it up to 8 gigs and works fine,

You may get a SQL DB error if so you will need to import the account IP table into my sql workbench using the import option once you do that you would need to import the missing table
https://github.com/Thrax989/SWGFlurry/tree/master/MMOCoreORB/sql/updates
you would need to add the Account_ips.sql


In version 02 ill have everything up to date.

**Comment by Gargash** [comment]
amazingly, it ran v1, no errors, building nav meshs now...

**Comment by Thrax989** [comment]
Nice, once it says core initialized your good to go for logging in.

**Comment by Thrax989** [comment]
Few messages will spam often since a few things still have logging enabled for testing nothing to worry about if you see a message spit out multiple times.

**Comment by Gargash** [comment]
Not worried about output server side ATM... how do i initiate a IP change... isn't it in Db and a config file?

**Comment by Thrax989** [comment]
Mysql workbench under the Galaxy table

**Comment by Gargash** [comment]
**slaps forehead** duh, i'm a real goof sometimes.

**Comment by Gargash** [comment]
i get to connecting to galaxy after selecting a galaxy screen and hang on connecting...... all i did was change it to an internal IP as i have 12 machines in the house that connect in various ways... all i changed was ip scheme to 192.168.1.xxx in the galaxy table and got nothing after 10 min.

**Comment by Thrax989** [comment]
I have not attempted to make the Vm public yet, I just run it locally on Lan with 127.0.0.1 might need to check ports, Firewall or the bridge connection.

**Comment by Gargash** [comment]
bridged connection has worked previously... im sure there is another area in a config that has it directed wrong and needs to be changed as well... Same case in a WoW server... there is a config and a DB IP entry.. I might hope on IRC and ask... why i suggested zdcfg as it changes whats required... i'lll start breaking it down and let you know.

**Comment by Gargash** [comment]
I totally understand what you are saying now.... I forgot im not working with an individual machine via VNC... its VM lmao. So if I change it from a bridged to NAT, again, then I can just use my machines local IP on the LAN with other machines too...  correct?

**Comment by Thrax989** [comment]
anyone at the house can connect to 127.0.0.1 if its running off of local. Update your login file before launching the client.

**Comment by Gargash** [comment]
switched to NAT.. changed login file IP. In and running. 

The IP check script came up when I switched adapters which corrected everything.

**Comment by Gargash** [comment]
so where can i find info on the grey jedi stuff? flurry forums?

**Comment by Thrax989** [comment]
the gray jedi stuff is on forums http://www.swgflurry.com/forum/showthread.php?tid=953 its a starting profession

**Comment by Gargash** [comment]
I know that... The grey Jedi trainer is what I really am looking for... Is it different from normal village or same?

**Comment by Gargash** [comment]
That's cool... I've already tweaked buffs and blue frog with 11250 skill points to just test everything since no-pop for the family. I am just trying to find the trainer for grey..... Very interested since I consider myself a grey Jedi, if I had to pick. So really just need trainer info was gonna look through the script but I figured you'd know faster.

**Comment by Gargash** [comment]
She is testing the spy class.....

**Comment by Thrax989** [comment]
the trainers should be in the village in a Hut, there should be 4 of them .

**Comment by Thrax989** [comment]
target yourself then do /gmjedistate 2
then you can spawn the trainers 

/createcreature trainer_combatjedigray
/createcreature trainer_combatjedigrayelder 
/createcreature trainer_combatjedigrayelderrank 
/createcreature trainer_combatjedigrayelderrankcouncil

**Comment by Thrax989** [comment]
The gray jedi profession has all 5 post publish 9 jedi profession skills within the entire gray jedi profession.

If you want to be a normal jedi that can only master up to 3 jedi professions you can grant them to you but the gray jedi class is locked in from start since it cost 250 points but it gives you everything

normal jedi can only max 3 templates gray can max all 5 since all the skills are in the entire tree

if you want to be a normal jedi target yourself

/gmjedistate 2
/grantskill force_title_jedi_novice

use this jedi terminal I created to learn the rest of the skills or you can train in the village.

/object createitem object/tangible/beta/beta_terminal_xp.iff

**Comment by Thrax989** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Submit a GitHub Server Issue Ticket](https://trello.com/c/pgxbGlNz/48-submit-a-github-server-issue-ticket)
