### ISSUE TITLE
Rebel faction point costs not consistent/broken

### ISSUE THREAD

**Issue by mikeface** [Thrax989/SWGFlurry#47]
Faction point cost is seemingly broken for rebels.  Race should not matter for rebels, and cost should go down with rank.  Example costs below.

Char one: Rodian, corporal
Alliance detachment HQ: 29250

Char two: Rodian, Second Lt
Alliance detachment HQ: 39000

Even same race, there's something odd that a lower rank has a lower cost than the higher rank.

**Comment by Thrax989** [comment]
https://github.com/Thrax989/SWGFlurry/commit/6a5ad2a14ffa0b05f883f973d713997f6fec645c
