### ISSUE TITLE
ranger harvesting

### ISSUE THREAD

**Issue by Bommbur** [Thrax989/SWGFlurry#5]
ranger harvesting at the moment is out of control, close to 50k resources can be harvested per lair, this needs to be brought down to at least 1/10th of this to like a maximum of 500 per resource harvested

**Comment by sygnum** [comment]
If this server was as populated as it was in live then I could see a need for this.. However, its not.. I believe this should be left alot. And I am sure alot of crafters will feel that way. Not everyone is rolling rangers and overloading the market with Ranger harvested goods.

**Comment by laughingowl** [comment]
Well guess bigger quesiotn if 50k of what.  PP a lair of Fambaa's and probably got well over 50k,  now if a lair of insects is giving 50k meat :-)  that might be a different story.  but PP I could get over 100k meat/hide as taped master ranger from a Famba lair, so if only 50k now dont think unreasonable

**Comment by Thrax989** [comment]
This has been changed Currently on the Test Server Please report any testing you do . https://github.com/Thrax989/SWGFlurry/commit/2b4692f518361465db42f149040eda6f0369e27b

**Comment by Aadye** [comment]
Tested and also used droid at different levels of Ranger harvesting.

**Comment by Thrax989** [comment]
This has been patched thank you . https://github.com/Thrax989/SWGFlurry/commit/2b4692f518361465db42f149040eda6f0369e27b
