### ISSUE TITLE
Missing Harvester Resources (On Snagga's behalf)

### ISSUE THREAD

**Issue by sygnum** [Thrax989/SWGFlurry#69]
Snagga original posted this on the forums

Went to Talus to check on my Flora farms that were pulling up the Talusian Tubers (Ono). They were all empty but 1 that had 47k in it. They should have had hundreds of thousands of units on each one (was on it since a few hours after spawn). It's the ten High Capacity Flora Farms that belong to Elsa at WP -6130 1100. Can anything be done about all my missing Tubers? Huh
I'll leave the harvesters in place until I can get an answer.
BTW, I didn't forget to turn them on and they had power and maintenance to run them for 2 weeks. I checked on them last week and they were under half full.

**Comment by Bommbur** [comment]
http://www.swgemu.com/bugs/view.php?id=6576

There has been numerous bugs related to harvesters over the years, opening the hopper but not retrieving the resources and come back and they are gone, turning the harvesters on to close to a server save/restart and not truly activating, maintenance running out will shut them down even though they pull from your bank on the costs.
All this being as it is, I have learned to check and pull completely the hopper loads from each harvester every few days to avoid these problems, its prolly a good idea for everyone.

**Comment by Thrax989** [comment]
<img src="http://i.imgur.com/huDBKud.jpg">

**Comment by sygnum** [comment]
Those are Cheeto's, Snagga was teaching helping him get into crafting and resource collecting. Which was why hes on admin for those.

**Comment by Thrax989** [comment]
Staff still needs to look into this or close . 

Managment 
CSR's
Admins
Please  close or follow up with the ticket. This is not a developers task.

**Comment by bobvious** [comment]
So we have reviewed this.   It appears to be a known bug that can happen.  We can't be in the mode of replacing everything that bugs out unfortunately.   If you had some visual evidence that the harvesters were full and then the resource disappeared, that would be a different story.  But we can't verify bug, or if you forgot to turn on (we've all done that).  Etc.  Our apologies for the frustration, but we can't act on this one.
