### ISSUE TITLE
Profession Check List

### ISSUE THREAD

**Issue by Thrax989** [Thrax989/SWGFlurry#8]
*Updated Profession Check List*
Profession Check List

1.Architect 100% complete 
2.Armorsmith 100% complete tested
3.Artisan 100 % complete maybe come back to thsi to add Crafted Vehicles 
4.Bio-Engineer 85% complete
5.Bounty Hunter 100% complete 
6.Brawler 100% complete 
7.Carbineer 100% complete
8.Chef 100% complete
9.Combat Medic 100% complete 
10.Commando 100% complete 
11.Creature Handler 85% complete
12.Dancer 100% complete 
13.Doctor 100% complete
14.Droid Engineer 100%complete
15.Entertainer 100% complete add human bonus
16.Fencer 100% complete
17.Image Designer 100% complete
18.Marksman 100% complete
19.Medic 100% complete
20.Merchant 100% complete
21.Musician 100% complete
22.Pikeman 100% complete
23.Pistoleer 100% complete
24.Politician100% complete
25.Ranger 100% complete
26.Rifleman 100% complete
27.Scout 100% complete
28.Shipwright 100% complete
29.Smuggler 100% complete
30.Squad Leader 100% complete
31.Swordsman 100% complete
32.Tailor 100% complete
33.Teras Kasi Artist 100% complete
34.Weaponsmith 100% complete

**Comment by Thrax989** [comment]
Remaining Testing Still before Launch
4.Bio-Engineer 50% complete
11.Creature Handler 50% complete
14.Droid Engineer 85%complete bomb droids need testing 
30.Squad Leader 85% complete

**Comment by PepiDeto** [comment]
I have completed the Factional Destroy missions.  The Banners are able to be targeted and destroyed.  Issue is fixed.

**Comment by Thrax989** [comment]
Ok thank you for testing that one more bug off the list.

**Comment by Thrax989** [comment]
Remaining Testing Still before Launch
4.Bio-Engineer 85% complete
11.Creature Handler 85% complete

**Comment by PepiDeto** [comment]
What if CH still needs to be done?
I have master but the frog isn't giving me any tapes to be able I check the Rancors...

**Comment by Thrax989** [comment]
https://github.com/Thrax989/SWGFlurry/commit/fcc31a97ad42df680d028dd23173c217ec660440
https://github.com/Thrax989/SWGFlurry/commit/e4227b37082d2132284483e391825097f1fc1ae1
these commits check them .

**Comment by PepiDeto** [comment]
Roger Roger.

**Comment by Thrax989** [comment]
https://github.com/Thrax989/SWGFlurry/commit/11555016af1ea4334c3d3f7b508cb58443c01b91

Last bit of be testing

**Comment by bobvious** [comment]
Closing this issue as we completed testing for launch.
