### ISSUE TITLE
NGE house bonus

### ISSUE THREAD

**Issue by Thrax989** [Thrax989/SWGFlurry#9]
-       {"private_medical_rating", 125},
 -      {"private_buff_mind", 125},
 -      {"private_med_battle_fatigue", 15},
 -      {"advanced_assembly", 50},
 -      {"armor_assembly", 50},
 -      {"general_assembly", 50},
 -      {"bio_engineer_assembly", 50},
 -      {"booster_assembly", 50},
 -      {"chassis_assembly", 50},
 -      {"clothing_assembly", 50},
 -      {"combat_medicine_assembly", 50},
 -      {"creature_assembly", 50},
 -      {"domestic_assembly", 50},
 -      {"droid_assembly", 50},
 -      {"engine_assembly", 50},
 -      {"engineering_assembly", 50},
 -      {"firearm_assembly", 50},
 -      {"food_assembly", 50},
 -      {"force_assembly", 50},
 -      {"grenade_assembly", 50},
 -      {"instrument_assembly", 50},
 -      {"jedi_saber_assembly", 50},
 -      {"medicine_assembly", 50},
 -      {"melee_assembly", 50},
 -      {"munition_assembly", 50},
 -      {"shields_assembly", 50},
 -      {"spice_assembly", 50},
 -      {"structure_assembly", 50},
 -      {"tissue_assembly", 50},
 -      {"weapon_assembly", 50},
 -      {"advanced_ship_experimentation", 50},
 -      {"armor_experimentation", 50},
 -      {"general_experimentation", 50},
 -      {"bio_engineer_experimentation", 50},
 -      {"booster_experimentation", 50},
 -      {"chassis_experimentation", 50},
 -      {"clothing_experimentation", 50},
 -      {"combat_medicine_experimentation", 50},
 -      {"creature_experimentation", 50},
 -      {"droid_experimentation", 50},
 -      {"engine_experimentation", 50},
 -      {"firearm_experimentation", 50},
 -      {"food_experimentation", 50},
 -      {"force_experimentation", 50},
 -      {"grenade_experimentation", 50},
 -      {"jedi_saber_experimentation", 50},
 -      {"medicine_experimentation", 50},
 -      {"melee_experimentation", 50},
 -      {"munition_experimentation", 50},
 -      {"power_systems_experimentation", 50},
 -      {"shields_experimentation", 50},
 -      {"spice_experimentation", 50},
 -      {"structure_experimentation", 50},
 -      {"tissue_experimentation", 50},
 -      {"weapon_experimentation", 50},
 -      {"weapon_systems_experimentation", 50},
 -      {"armor_complexity", 50},
 -      {"clothing_complexity", 50},
 -      {"medicine_complexity", 50},
 -      {"droid_complexity", 50},
 -      {"firearm_complexity", 50},
 -      {"food_complexity", 50},
 -      {"melee_complexity", 50},
 -      {"munition_complexity", 50},
 -      {"structure_complexity", 50},
 -      {"armor_customization", 50},
 -      {"artisan_clothing_customization", 50},
 -      {"clothing_customization", 50},
 -      {"droid_customization", 50},
 -      {"armor_repair", 50},
 -      {"clothing_repair", 50},
 -      {"force_repair_bonus", 50},
 -      {"crafting_repair", 50},
 -      {"weapon_repair", 50},
 -      {"combat_medic_effectiveness", 50},
 -      {"general_damage", 50},
 -      {"shop_sign", 50},
 -      {"sales", 50},
 -      {"structure_maintenance_mod", 50}

**Comment by Bommbur** [comment]
Im thinking Assembly bonuses, customization, repairs, put experimentations to 5 so that a half point will be added to fully taped crafters to equal out 13 points no jedi crafters.

Medical and Entertainer portions  {"private_medical_rating", 125},
 {"private_buff_mind", 125},
 {"private_med_battle_fatigue", 15},  should be relegated to cantinas and med centers

**Comment by Bommbur** [comment]
Ok so remove the first 3 related to med/ent, reduce experimentation to 5 on all, leave the rest

**Comment by Bommbur** [comment]
{"advanced_assembly", 50},
 {"armor_assembly", 50},
 {"general_assembly", 50},
 {"bio_engineer_assembly", 50},
 {"clothing_assembly", 50},
 {"combat_medicine_assembly", 50},
 {"droid_assembly", 50},
 {"engineering_assembly", 50},
 {"food_assembly", 50},
 {"force_assembly", 50},
 {"jedi_saber_assembly", 50},
 {"medicine_assembly", 50},
 {"structure_assembly", 50},
 {"weapon_assembly", 50},

 {"armor_experimentation", 5},
 {"general_experimentation", 5},
 {"bio_engineer_experimentation", 5},
 {"clothing_experimentation", 5},
 {"combat_medicine_experimentation", 5},
 {"creature_experimentation", 5},
 {"droid_experimentation", 5},
 {"food_experimentation", 5},
 {"force_experimentation", 5},
 {"jedi_saber_experimentation", 5},
 {"medicine_experimentation", 5},
 {"structure_experimentation", 5},
 {"tissue_experimentation", 5},
 {"weapon_experimentation", 5},

 {"armor_complexity", 50},
 {"clothing_complexity", 50},
 {"medicine_complexity", 50},
 {"droid_complexity", 50},
 {"food_complexity", 50},
 {"structure_complexity", 50},
 {"armor_customization", 50},
 {"artisan_clothing_customization", 50},
 {"clothing_customization", 50},
 {"droid_customization", 50},

 {"armor_repair", 50},
 {"clothing_repair", 50},
 {"force_repair_bonus", 50},
 {"crafting_repair", 50},
 {"weapon_repair", 50},

**Comment by Thrax989** [comment]
use the above skill mods for nge house.

**Comment by mhutcherson** [comment]
Changes are committed and waiting to be pulled in. Can be closed.
